import 'package:isar/isar.dart';

part 'document_model.g.dart'; // generated by build_runner

/// A single scanned page belonging to a [ScanDocument].
/// Embedded object — stored inline inside the parent document, not its own collection.
@embedded
class ScanPage {
  late String localImagePath; // absolute path inside app sandbox, never uploaded
  String? ocrText;            // null until OCR has run
  int order = 0;              // drives drag-and-drop sequence before PDF compile
}

@collection
class ScanDocument {
  Id id = Isar.autoIncrement;

  late String title;

  @Index()
  late DateTime createdAt;

  late DateTime updatedAt;

  List<ScanPage> pages = [];

  /// Path to the compiled PDF once exported. Null while still a draft.
  String? pdfPath;

  /// True if the PDF was written with a user password via [PdfService].
  bool isPasswordProtected = false;

  /// Vault flag — surfaced as a lock badge in the dashboard grid.
  bool isInSecureVault = false;

  int get pageCount => pages.length;
}
